from tests.page_objects.base_page import BasePage
from tests.page_objects.landing_page import LandingPage
from tests.page_objects.auth_page import AuthPage
from tests.page_objects.dashboard_page import DashboardPage
from tests.page_objects.interview_page import InterviewPage
from tests.page_objects.results_page import ResultsPage
from tests.page_objects.history_page import HistoryPage
from tests.page_objects.resume_page import ResumePage
from tests.page_objects.profile_page import ProfilePage
